groups: []

resource_types:
- name: bosh-creds
  type: docker-image
  source:
    repository: dlapiduz/bosh-creds-resource
    tag: latest

resources:
- name: pcf-prometheus-git
  type: git
  source:
    uri: https://github.com/dlapiduz/pcf-prometheus-pipeline.git
    branch: master
- name: pcf-prometheus-manifest
  type: git
  source:
    uri: https://github.com/dlapiduz/prometheus-on-PCF.git
    branch: master
- name: prometheus-release
  type: github-release
  source:
    user: dlapiduz
    repository: prometheus-boshrelease
    access_token: {{github_token}}
- name: om-bosh-creds
  type: bosh-creds
  source:
    pcf_ert_domain: {{pcf_ert_domain}}
    pcf_opsman_admin_username: {{pcf_opsman_admin_username}}
    pcf_opsman_admin_password: {{pcf_opsman_admin_password}}

jobs:
- name: create-uaa-creds
  plan:
  - aggregate:
    - get: pcf-prometheus-git
  - task: create-uaa-creds
    file: pcf-prometheus-git/tasks/create-uaa-creds.yml
    params:
      pcf_ert_domain: {{pcf_ert_domain}}
      pcf_opsman_admin_username: {{pcf_opsman_admin_username}}
      pcf_opsman_admin_password: {{pcf_opsman_admin_password}}
      pcf_sys_domain: {{pcf_sys_domain}}
      prometheus_secret: {{prometheus_secret}}

- name: upload-release
  plan:
  - aggregate:
    - get: pcf-prometheus-git
      trigger: true
    - get: prometheus-release
    - get: om-bosh-creds
  - task: upload-release
    file: pcf-prometheus-git/tasks/upload-release.yml

- name: deploy
  plan:
  - aggregate:
    - get: pcf-prometheus-git
      trigger: true
    - get: om-bosh-creds
      passed: [upload-release]
    - get: pcf-prometheus-manifest
      trigger: true
  - task: deploy
    file: pcf-prometheus-git/tasks/deploy.yml
    params:
      prometheus_secret: {{prometheus_secret}}
      azs: {{deploy_azs}}
      network_name: {{deploy_network}}
      vm_password: {{deploy_vm_password}}
      nginx_ip: {{deploy_nginx_ip}}
      pcf_sys_domain: {{pcf_sys_domain}}
      pcf_ert_domain: {{pcf_ert_domain}}
      pcf_opsman_admin_username: {{pcf_opsman_admin_username}}
      pcf_opsman_admin_password: {{pcf_opsman_admin_password}}
